package com.seek.assignment.branding.localTokens

interface LocalSpacingTokens {
    val verticalSpacing2: Int
    val horizontalSpacing2: Int
    val verticalSpacing4: Int
    val horizontalSpacing4: Int
    val horizontalSpacing8: Int
    val verticalSpacing8: Int
    val verticalSpacing12: Int
    val horizontalSpacing12: Int
    val verticalPadding16: Int
    val horizontalPadding16: Int
    val verticalSpacing24: Int
    val horizontalSpacing24: Int
    val verticalSpacing32: Int
    val horizontalSpacing32: Int
    val verticalSpacing40: Int
    val horizontalSpacing40: Int
    val verticalSpacing48: Int
    val horizontalSpacing48: Int
    val verticalSpacing56: Int
    val horizontalSpacing56: Int
    val verticalSpacing64: Int
    val horizontalSpacing64: Int
    val verticalSpacing72: Int
    val horizontalSpacing72: Int
    val verticalSpacing128: Int
    val horizontalSpacing128: Int
    val verticalSpacing256: Int
    val horizontalSpacing256: Int
    val verticalSpacing512: Int
    val horizontalSpacing512: Int
    val verticalSpacing80: Int
    val horizontalSpacing80: Int
    val horizontalSpacing16: Int
    val verticalSpacing16: Int
    val verticalPadding4: Int
    val horizontalPadding4: Int
    val verticalPadding8: Int
    val horizontalPadding8: Int
    val verticalPadding12: Int
    val horizontalPadding12: Int
    val verticalPadding2: Int
    val horizontalPadding2: Int
    val verticalPadding24: Int
    val horizontalPadding24: Int
    val verticalPadding32: Int
    val horizontalPadding32: Int
    val verticalPadding40: Int
    val horizontalPadding40: Int
    val verticalPadding48: Int
    val horizontalPadding48: Int
    val verticalPadding56: Int
    val horizontalPadding56: Int
    val verticalPadding64: Int
    val horizontalPadding64: Int
    val verticalPadding72: Int
    val horizontalPadding72: Int
    val verticalPadding80: Int
    val horizontalPadding80: Int
    val verticalPadding128: Int
    val horizontalPadding128: Int
    val verticalPadding256: Int
    val horizontalPadding256: Int
    val verticalPadding512: Int
    val horizontalPadding512: Int
}