package com.seek.assignment.branding.localTokens

interface LocalSizeTokens {
    val buttonHeightBig: Int
    val dividerHeightThin: Int
    val dividerHeightThick: Int
    val buttonHeightMedium: Int
    val buttonHeightSmall: Int
    val iconSize24: Int
    val listItemHeightSmall: Int
    val listItemHeightLarge: Int
    val iconSize16: Int
    val checkboxSize: Int
    val radioButtonSize: Int
    val radioButtonFill: Int
    val inputHeight: Int
    val buttonBigMinWidth: Int
    val inputHeightCommentBox: Int
    val stackButtonTopBottomHeight: Int
    val iconSize48: Int
    val b: Int
    val tabSelectionHeight: Int
    val tabHeight: Int
    val headlineSectionHeight: Int
    val chipHeight: Int
    val iconSize32: Int
    val renderSizeBig: Int
    val renderSizeMedium: Int
    val renderSizeSmall: Int
    val airQualityValueSize: Int
    val sliderIndicatorHeight: Int
    val weekdayPickerHeight64: Int
    val timelineIndicatorSize: Int
    val tabSelectionHeightSmall: Int
    val tabHeightSmall: Int
    val graphDataLineCircleSize: Int
    val graphDataLineCircleSmallSize: Int
    val listItemDividerHeight: Int
    val zoneControlCornerHandleSize: Int
    val zoneControlMidHandleWidth: Int
    val zoneControlMidHandleHeight: Int
    val strokeDashSize: Int
    val strokeGapSize: Int
    val pageControlCircleSize: Int
    val pageControlCircleSizeSmall: Int
    val chipMinWidth: Int
    val renderSizeXsmall: Int
    val illustrationHeightBig: Int
}