package com.seek.assignment.branding.localTokens

interface LocalColorTokens {
    val bottomNavColor: Long
    val bottomNavActiveTab: Long
    val bottomNavInactiveTab: Long
    val dividerColorPrimaryGrey: Long
    val homeIndicatorColor: Long
    val topNavColor: Long
    val topNavTitleColor: Long
    val topNavIconColor: Long
    val statusBarFillColorAndroid: Long
    val statusBarColorBlack: Long
    val listItemColor: Long
    val listItemCategoryIconColor: Long
    val listItemNavigationIconColor: Long
    val listItemTitleColor: Long
    val backgroundColor: Long
    val textSecondary: Long
    val listItemDescriptionCaptionColor: Long
    val textPrimary: Long
    val primaryCtaContentColor: Long
    val primaryCtaColor: Long
    val primaryCtaInvertedContentColor: Long
    val primaryCtaInvertedColor: Long
    val checkboxUnselectedColor: Long
    val checkboxSelectedColor: Long
    val checkboxIconColor: Long
    val radioButtonUnselectedColor: Long
    val radioButtonSelectedColor: Long
    val switchOffColor: Long
    val switchHandleColorIos: Long
    val switchOnColor: Long
    val switchOnHandleColorAndroid: Long
    val switchOffHandleColorAndroid: Long
    val secondaryCtaContentColor: Long
    val secondaryCtaStrokeColor: Long
    val secondaryCtaInvertedContentColor: Long
    val secondaryCtaInvertedStrokeColor: Long
    val textCtaContentColor: Long
    val textCtaFillPressedColor: Long
    val textCtaInvertedContentColor: Long
    val textCtaInvertedFillPressedColor: Long
    val inputColor: Long
    val inputActiveColor: Long
    val inputErrorColor: Long
    val inputHelperColor: Long
    val inputTextColor: Long
    val inputIconColor: Long
    val splashBackgroundColor: Long
    val iconTintColor: Long
    val snackbarFillDefaultColor: Long
    val snackbarFillErrorColor: Long
    val snackbarContentColor: Long
    val snackbarActionColor: Long
    val secondaryCtaInvertedFillColor: Long
    val textCtaFillColor: Long
    val textCtaInvertedFillColor: Long
    val statusBarColorWhite: Long
    val topNavColorTransparent: Long
    val topNavIconBackgroundFillColor: Long
    val topBarModalBackgroundColor: Long
    val topNavModalBackSheetColor: Long
    val secondaryCtaFillColor: Long
    val popupActionColor: Long
    val popupActionCriticalColor: Long
    val feedCardBackgroundColor: Long
    val feedTextTitleColor: Long
    val feedTextOtherColor: Long
    val feedIconColor: Long
    val feedListIconColor: Long
    val feedCardBackgroundColorSurface: Long
    val listItemColorSurface: Long
    val surfaceColor: Long
    val inputColorSurface: Long
    val topNavSurfaceColor: Long
    val overlayBackgroundColor: Long
    val dividerColorSecondaryGrey: Long
    val iconTintInvertedColor: Long
    val illustrationDefaultColor: Long
    val illustrationAccentColor: Long
    val textPrimaryInverted: Long
    val cardHeadlineColor: Long
    val cardTextColor: Long
    val cardBgColor: Long
    val cardIconColor: Long
    val cardBgColorSurface: Long
    val cardStrokeColor: Long
    val tabBgColor: Long
    val tabBgColorCard: Long
    val tabActiveColor: Long
    val tabUnselectedContentColor: Long
    val cardStrokeColorSurface: Long
    val tabBgColorSurface: Long
    val tabBgColorSurfaceCard: Long
    val tabActiveContentColor: Long
    val headlineTitleColor: Long
    val headlineIconColor: Long
    val headlineActionColor: Long
    val listCheckSelectionText: Long
    val chipTextColor: Long
    val chipBgColor: Long
    val chipSelectedBgColor: Long
    val chipSelectedTextColor: Long
    val snackbarContentErrorColor: Long
    val snackbarActionErrorColor: Long
    val chipBgColorSurface: Long
    val menuContentColor: Long
    val menuBgColor: Long
    val menuSelectedBgColor: Long
    val productCardErrorColor: Long
    val productCardBackgroundColor: Long
    val productCardPrimaryTextColor: Long
    val productCardSecondaryTextColor: Long
    val menuSelectedColor: Long
    val controlCardBackgroundColor: Long
    val controlCardSurfaceColor: Long
    val sliderActiveColor: Long
    val sliderTrackBackgroundColor: Long
    val sliderTickMarkColor: Long
    val sliderThumbColor: Long
    val sliderValueLabelBackgroundColor: Long
    val sliderValueLabelColor: Long
    val controlCardIconColor: Long
    val textSecondaryInverted: Long
    val heroContentColor: Long
    val heroIconError: Long
    val sliderTrackSurfaceColor: Long
    val sliderValueLabelSurfaceColor: Long
    val indicatorColor: Long
    val cardDataNeutralColor: Long
    val textError: Long
    val taskCardBackgroundColor: Long
    val taskCardPrimaryTextColor: Long
    val taskCardSecondaryTextColor: Long
    val taskIconColor: Long
    val taskListIconColor: Long
    val popupPrimaryTextColor: Long
    val popupSecondaryTextColor: Long
    val popupIconColor: Long
    val popupBackgroundColor: Long
    val pickerSelectionIosColor: Long
    val pickerSelectionIosColorSurface: Long
    val iconErrorColor: Long
    val aqiAsiaGood: Long
    val aqiVeryGood: Long
    val aqiEuGood: Long
    val aqiPoor: Long
    val aqiVeryPoor: Long
    val aqiBad: Long
    val aqiVeryBad: Long
    val indicatorInactiveColor: Long
    val timelineStrokeColor: Long
    val timelineActiveBackgroundColor: Long
    val timelineCheckedBackgroundColor: Long
    val timelineErrorColor: Long
    val timelineTitleColor: Long
    val timelineCaptionColor: Long
    val timelineIndicatorIconColor: Long
    val timelineCheckedIconColor: Long
    val listHorizontalTitleColor: Long
    val listHorizontalCaptionColor: Long
    val mapPermanentMap: Long
    val mapCleanedAreaColor: Long
    val zoneStrokeColor: Long
    val zoneAvoidColor: Long
    val timelineIndicatorIconInvertedColor: Long
    val timelineChargingBackgroundColor: Long
    val headlineBodyColor: Long
    val graphGridColor: Long
    val graphDataLineColor: Long
    val graphDataDashedLineColor: Long
    val graphActiveLineColor: Long
    val graphBarColor: Long
    val graphTextColor: Long
    val graphActiveBarColor: Long
    val indicatorSheetColor: Long
    val chipZoneAvoidBgColor: Long
    val mapZoneControlColor: Long
    val mapZoneAvoidControlColor: Long
    val textCtaContentColorGrey: Long
    val secondaryCtaFillPressedColor: Long
    val badgeTextColor: Long
    val badgeBackgroundColor: Long
    val chipZoneBackgroundColor: Long
    val chipZoneTextColor: Long
    val chipZoneAvoidTextColor: Long
    val cardIconActionColor: Long
    val sliderInactiveBackgroundColor: Long
    val sliderInactiveSurfaceColor: Long
    val dividerColorBackgroundCard: Long
    val dividerColorSurfaceCard: Long
    val dividerColorSurface: Long
    val dividerColorBackground: Long
    val heroIconSecondaryColor: Long
    val heroIconColor: Long
    val timerActiveLine: Long
    val timerDefaultLineBackgroundColor: Long
    val timerContent: Long
    val timerDefaultLineSurfaceColor: Long
    val cardDataIconColor: Long
    val buttonSquareIconColor: Long
    val cardSelectionColor: Long
    val testColor: Long
    val controlCardInactiveIconColor: Long
    val badgeInactiveBackgroundColor: Long
    val graphGridColorSurface: Long
    val iconGreyColor: Long
    val graphBarFeedColor: Long
    val textCircleColor: Long
}